/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GeminiRouteImport } from './routes/gemini'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CbseMandatoryDisclosureRouteImport } from './routes/cbse-mandatory-disclosure'
import { Route as AskQuestionsRouteImport } from './routes/ask-questions'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageSpsLoginRouteImport } from './routes/manage-sps/login'
import { Route as ManageSpsLayoutRouteImport } from './routes/manage-sps/_layout'
import { Route as ApiAskGeminiRouteImport } from './routes/api.ask-gemini'
import { Route as ManageSpsLayoutIndexRouteImport } from './routes/manage-sps/_layout/index'
import { Route as ManageSpsLayoutGalleryRouteImport } from './routes/manage-sps/_layout/gallery'

const GeminiRoute = GeminiRouteImport.update({
  id: '/gemini',
  path: '/gemini',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CbseMandatoryDisclosureRoute = CbseMandatoryDisclosureRouteImport.update({
  id: '/cbse-mandatory-disclosure',
  path: '/cbse-mandatory-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const AskQuestionsRoute = AskQuestionsRouteImport.update({
  id: '/ask-questions',
  path: '/ask-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageSpsLoginRoute = ManageSpsLoginRouteImport.update({
  id: '/manage-sps/login',
  path: '/manage-sps/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageSpsLayoutRoute = ManageSpsLayoutRouteImport.update({
  id: '/manage-sps/_layout',
  path: '/manage-sps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskGeminiRoute = ApiAskGeminiRouteImport.update({
  id: '/api/ask-gemini',
  path: '/api/ask-gemini',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageSpsLayoutIndexRoute = ManageSpsLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageSpsLayoutRoute,
} as any)
const ManageSpsLayoutGalleryRoute = ManageSpsLayoutGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => ManageSpsLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/ask-questions': typeof AskQuestionsRoute
  '/cbse-mandatory-disclosure': typeof CbseMandatoryDisclosureRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/gemini': typeof GeminiRoute
  '/api/ask-gemini': typeof ApiAskGeminiRoute
  '/manage-sps': typeof ManageSpsLayoutRouteWithChildren
  '/manage-sps/login': typeof ManageSpsLoginRoute
  '/manage-sps/gallery': typeof ManageSpsLayoutGalleryRoute
  '/manage-sps/': typeof ManageSpsLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/ask-questions': typeof AskQuestionsRoute
  '/cbse-mandatory-disclosure': typeof CbseMandatoryDisclosureRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/gemini': typeof GeminiRoute
  '/api/ask-gemini': typeof ApiAskGeminiRoute
  '/manage-sps/login': typeof ManageSpsLoginRoute
  '/manage-sps/gallery': typeof ManageSpsLayoutGalleryRoute
  '/manage-sps': typeof ManageSpsLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/ask-questions': typeof AskQuestionsRoute
  '/cbse-mandatory-disclosure': typeof CbseMandatoryDisclosureRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/gemini': typeof GeminiRoute
  '/api/ask-gemini': typeof ApiAskGeminiRoute
  '/manage-sps/_layout': typeof ManageSpsLayoutRouteWithChildren
  '/manage-sps/login': typeof ManageSpsLoginRoute
  '/manage-sps/_layout/gallery': typeof ManageSpsLayoutGalleryRoute
  '/manage-sps/_layout/': typeof ManageSpsLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/ask-questions'
    | '/cbse-mandatory-disclosure'
    | '/contact'
    | '/gallery'
    | '/gemini'
    | '/api/ask-gemini'
    | '/manage-sps'
    | '/manage-sps/login'
    | '/manage-sps/gallery'
    | '/manage-sps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/ask-questions'
    | '/cbse-mandatory-disclosure'
    | '/contact'
    | '/gallery'
    | '/gemini'
    | '/api/ask-gemini'
    | '/manage-sps/login'
    | '/manage-sps/gallery'
    | '/manage-sps'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/ask-questions'
    | '/cbse-mandatory-disclosure'
    | '/contact'
    | '/gallery'
    | '/gemini'
    | '/api/ask-gemini'
    | '/manage-sps/_layout'
    | '/manage-sps/login'
    | '/manage-sps/_layout/gallery'
    | '/manage-sps/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicsRoute: typeof AcademicsRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AskQuestionsRoute: typeof AskQuestionsRoute
  CbseMandatoryDisclosureRoute: typeof CbseMandatoryDisclosureRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  GeminiRoute: typeof GeminiRoute
  ApiAskGeminiRoute: typeof ApiAskGeminiRoute
  ManageSpsLayoutRoute: typeof ManageSpsLayoutRouteWithChildren
  ManageSpsLoginRoute: typeof ManageSpsLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gemini': {
      id: '/gemini'
      path: '/gemini'
      fullPath: '/gemini'
      preLoaderRoute: typeof GeminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cbse-mandatory-disclosure': {
      id: '/cbse-mandatory-disclosure'
      path: '/cbse-mandatory-disclosure'
      fullPath: '/cbse-mandatory-disclosure'
      preLoaderRoute: typeof CbseMandatoryDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-questions': {
      id: '/ask-questions'
      path: '/ask-questions'
      fullPath: '/ask-questions'
      preLoaderRoute: typeof AskQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-sps/login': {
      id: '/manage-sps/login'
      path: '/manage-sps/login'
      fullPath: '/manage-sps/login'
      preLoaderRoute: typeof ManageSpsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-sps/_layout': {
      id: '/manage-sps/_layout'
      path: '/manage-sps'
      fullPath: '/manage-sps'
      preLoaderRoute: typeof ManageSpsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask-gemini': {
      id: '/api/ask-gemini'
      path: '/api/ask-gemini'
      fullPath: '/api/ask-gemini'
      preLoaderRoute: typeof ApiAskGeminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-sps/_layout/': {
      id: '/manage-sps/_layout/'
      path: '/'
      fullPath: '/manage-sps/'
      preLoaderRoute: typeof ManageSpsLayoutIndexRouteImport
      parentRoute: typeof ManageSpsLayoutRoute
    }
    '/manage-sps/_layout/gallery': {
      id: '/manage-sps/_layout/gallery'
      path: '/gallery'
      fullPath: '/manage-sps/gallery'
      preLoaderRoute: typeof ManageSpsLayoutGalleryRouteImport
      parentRoute: typeof ManageSpsLayoutRoute
    }
  }
}

interface ManageSpsLayoutRouteChildren {
  ManageSpsLayoutGalleryRoute: typeof ManageSpsLayoutGalleryRoute
  ManageSpsLayoutIndexRoute: typeof ManageSpsLayoutIndexRoute
}

const ManageSpsLayoutRouteChildren: ManageSpsLayoutRouteChildren = {
  ManageSpsLayoutGalleryRoute: ManageSpsLayoutGalleryRoute,
  ManageSpsLayoutIndexRoute: ManageSpsLayoutIndexRoute,
}

const ManageSpsLayoutRouteWithChildren = ManageSpsLayoutRoute._addFileChildren(
  ManageSpsLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicsRoute: AcademicsRoute,
  AdmissionsRoute: AdmissionsRoute,
  AskQuestionsRoute: AskQuestionsRoute,
  CbseMandatoryDisclosureRoute: CbseMandatoryDisclosureRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  GeminiRoute: GeminiRoute,
  ApiAskGeminiRoute: ApiAskGeminiRoute,
  ManageSpsLayoutRoute: ManageSpsLayoutRouteWithChildren,
  ManageSpsLoginRoute: ManageSpsLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
